name: GH Actions Cron Schedule
on:
  workflow_dispatch:
  schedule:
    # Every M-F at 12:00am run this job
    - cron:  "0 0 * * 1-5"
    
jobs:
  check-image-version:
    uses: JasonPowr/actions/.github/workflows/check-image-version.yaml@add-extra-check-for-check-image-version
    with:
      mainRef: main
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}